# House Price vol 2

# マッピングしたデータで分析してみる

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline


In [3]:
data_train = pd.read_csv('House Price Mapping train.csv')
data_test = pd.read_csv('House Price Mapping test.csv')
data_train.head()
print(data_train.shape)
data_test.head()
data_train.describe()

(1460, 24)


MSSubClass  Neighborhood  OverallQual    YearBuilt  YearRemodAdd  \
count  1460.000000   1460.000000  1460.000000  1460.000000   1460.000000   
mean      9.731507     11.973973     5.099315    64.708904     33.927397   
std       3.884624      6.425884     1.382997    30.944680     19.890452   
min       0.000000      0.000000     0.000000     0.000000      0.000000   
25%       6.000000      6.000000     4.000000    40.000000     16.000000   
50%      11.000000     12.000000     5.000000    67.500000     41.000000   
75%      13.000000     16.000000     6.000000    95.000000     51.000000   
max      14.000000     24.000000     9.000000   111.000000     60.000000   

        MasVnrType   MasVnrArea   ExterQual   Foundation     BsmtQual  \
count  1460.000000  1460.000000  1460.00000  1460.000000  1460.000000   
mean      1.472452   103.685262     1.39589     3.204795     1.579761   
std       0.666386   180.569112     0.57428     1.648263     0.671916   
min       0.000000     0.000000     0.00000     0.000000     0.000000   
25%       1.000000     0.000000     1.00000     2.000000     1.000000   
50%       1.000000     0.000000     1.00000     2.000000     2.000000   
75%       2.000000   164.250000     2.00000     5.000000     2.000000   
max       3.000000  1600.000000     3.00000     5.000000     3.000000   

           ...           FullBath  KitchenQual  TotRmsAbvGrd   Fireplaces  \
count      ...        1460.000000  1460.000000   1460.000000  1460.000000   
mean       ...           1.126027     1.511644      4.774658     0.613014   
std        ...           1.022975     0.663760      2.031429     0.644666   
min        ...           0.000000     0.000000      0.000000     0.000000   
25%        ...           0.000000     1.000000      3.000000     0.000000   
50%        ...           2.000000     1.000000      4.000000     1.000000   
75%        ...           2.000000     2.000000      5.000000     1.000000   
max        ...           3.000000     3.000000     11.000000     3.000000   

        GarageType  GarageYrBlt  GarageFinish   GarageCars   GarageArea  \
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000   
mean      3.173314    59.469906      0.816534     1.887671   472.980137   
std       1.389172    24.984704      0.790009     0.980823   213.804841   
min       0.000000     0.000000      0.000000     0.000000     0.000000   
25%       1.000000    41.000000      0.000000     1.000000   334.500000   
50%       4.000000    60.000000      1.000000     2.000000   480.000000   
75%       4.000000    81.000000      1.000000     2.000000   576.000000   
max       5.000000    96.000000      2.000000     4.000000  1418.000000   

           SalePrice  
count    1460.000000  
mean   180921.195890  
std     79442.502883  
min     34900.000000  
25%    129975.000000  
50%    163000.000000  
75%    214000.000000  
max    755000.000000  

[8 rows x 24 columns]

In [23]:
a = data_train.corr()
b = a[a.SalePrice > 0.6]
b

MSSubClass  Neighborhood  OverallQual  YearBuilt  YearRemodAdd  \
Neighborhood    0.532233      1.000000     0.667647   0.683095      0.521638   
OverallQual     0.471136      0.667647     1.000000   0.665203      0.552825   
YearBuilt       0.572252      0.683095     0.665203   1.000000      0.652419   
ExterQual       0.393934      0.631870     0.726278   0.638206      0.570870   
BsmtQual        0.423389      0.629227     0.644946   0.707715      0.545541   
TotalBsmtSF     0.291599      0.456092     0.537808   0.434021      0.328112   
1stFlrSF        0.237884      0.405290     0.476224   0.349924      0.295100   
GrLivArea       0.347673      0.411751     0.593007   0.369635      0.325158   
KitchenQual     0.391700      0.566358     0.673331   0.575836      0.611669   
GarageCars      0.397369      0.585252     0.628715   0.570728      0.433995   
GarageArea      0.387789      0.529629     0.562022   0.523139      0.390554   
SalePrice       0.476982      0.696882     0.790982   0.619545      0.535370   

              MasVnrType  MasVnrArea  ExterQual  Foundation  BsmtQual  \
Neighborhood    0.400196    0.368029   0.631870    0.576118  0.629227   
OverallQual     0.449358    0.410238   0.726278    0.568969  0.644946   
YearBuilt       0.420443    0.298983   0.638206    0.699337  0.707715   
ExterQual       0.415825    0.349637   1.000000    0.597832  0.638241   
BsmtQual        0.393052    0.314065   0.638241    0.621976  1.000000   
TotalBsmtSF     0.374961    0.362452   0.470580    0.357950  0.410438   
1stFlrSF        0.343786    0.342160   0.397835    0.208966  0.362984   
GrLivArea       0.248026    0.389893   0.435986    0.282314  0.369656   
KitchenQual     0.362377    0.285190   0.716122    0.533146  0.562345   
GarageCars      0.429343    0.404375   0.557218    0.458128  0.545306   
GarageArea      0.380290    0.372567   0.495778    0.398155  0.458693   
SalePrice       0.426997    0.475241   0.682639    0.505503  0.635361   

                ...      FullBath  KitchenQual  TotRmsAbvGrd  Fireplaces  \
Neighborhood    ...      0.513701     0.566358      0.282979    0.315569   
OverallQual     ...      0.552153     0.673331      0.423438    0.396765   
YearBuilt       ...      0.555510     0.575836      0.246057    0.214032   
ExterQual       ...      0.497192     0.716122      0.308004    0.249335   
BsmtQual        ...      0.523471     0.562345      0.238832    0.227714   
TotalBsmtSF     ...      0.328368     0.432630      0.265278    0.339519   
1stFlrSF        ...      0.383710     0.387027      0.392750    0.410531   
GrLivArea       ...      0.613537     0.420563      0.809778    0.461679   
KitchenQual     ...      0.439960     1.000000      0.295499    0.256409   
GarageCars      ...      0.476583     0.535777      0.399737    0.300840   
GarageArea      ...      0.416933     0.489606      0.331666    0.269141   
SalePrice       ...      0.553851     0.659600      0.537672    0.466929   

              GarageType  GarageYrBlt  GarageFinish  GarageCars  GarageArea  \
Neighborhood    0.456575     0.579489      0.466576    0.585252    0.529629   
OverallQual     0.420713     0.574261      0.491404    0.628715    0.562022   
YearBuilt       0.519992     0.768672      0.554784    0.570728    0.523139   
ExterQual       0.378696     0.590883      0.482143    0.557218    0.495778   
BsmtQual        0.424760     0.642954      0.525068    0.545306    0.458693   
TotalBsmtSF     0.323174     0.337550      0.335570    0.471133    0.486665   
1stFlrSF        0.305210     0.251468      0.296095    0.464177    0.489782   
GrLivArea       0.292680     0.310591      0.319453    0.490960    0.468997   
KitchenQual     0.339323     0.536959      0.423690    0.535777    0.489606   
GarageCars      0.264771     0.485292      0.365879    1.000000    0.865866   
GarageArea      0.209133     0.462037      0.301241    0.865866    1.000000   
SalePrice       0.430770     0.535419      0.496031    0.692360    0.623431   

      

In [5]:
c = list(b.index)
c
c.remove('SalePrice')
c
d = pd.DataFrame(data_train, columns = c)
d.head()
e = pd.DataFrame(data_train, columns = ['SalePrice'])
e.head()
f = pd.concat([d, e], axis = 1)
f.head()
len(c)

11

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_std = sc.fit_transform(d)
y=sc.fit_transform(e)


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size = 0.3, random_state = 0)

In [26]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [ ]:
from sklearn.linear_model import 

In [27]:
lr.intercept_
lr.coef_

array([[ 0.1600952 ,  0.17211082, -0.01817159,  0.04553846,  0.09469509,
         0.14770497,  0.04699898,  0.32650122,  0.10136996,  0.09072272,
         0.02838088]])

In [28]:
lr.score(X_train, y_train)
lr.score(X_test, y_test)

0.75714582056838364

In [29]:
def adjusted(score, n_samples, n_features):
    adjusted = 1 - (1 - score)*((n_samples - 1)/(n_samples - n_features -1))
    return adjusted

In [30]:
print('train: %.4f' % adjusted(lr.score(X_train, y_train), len(y_train), 11 ))
print('test : %.4f' % adjusted(lr.score(X_test, y_test), len(y_test), 11))

train: 0.8276
test : 0.7509


In [31]:
from sklearn.preprocessing import PolynomialFeatures 
pf = PolynomialFeatures(degree = 7)
pf_cubic = pf.fit_transform(d)
pf_cubic

array([[  1.00000000e+00,   1.60000000e+01,   6.00000000e+00, ...,
          1.97680023e+14,   5.41643264e+16,   1.48410254e+19],
       [  1.00000000e+00,   2.00000000e+01,   5.00000000e+00, ...,
          8.23851904e+13,   1.89485938e+16,   4.35817657e+18],
       [  1.00000000e+00,   1.60000000e+01,   6.00000000e+00, ...,
          3.32336382e+14,   1.01030260e+17,   3.07131991e+19],
       ..., 
       [  1.00000000e+00,   1.70000000e+01,   6.00000000e+00, ...,
          1.01625502e+12,   2.56096265e+14,   6.45362588e+16],
       [  1.00000000e+00,   1.00000000e+01,   4.00000000e+00, ...,
          7.96262400e+11,   1.91102976e+14,   4.58647142e+16],
       [  1.00000000e+00,   4.00000000e+00,   4.00000000e+00, ...,
          1.60156810e+12,   4.42032796e+14,   1.22001052e+17]])

In [14]:
pf_cubic_train, pf_cubic_test, y_train, y_test = train_test_split(d, e, test_size = 0.3, random_state = 0)

In [15]:
from sklearn.linear_model import LinearRegression
ld = LinearRegression()
ld.fit(pf_cubic_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
ld.intercept_
ld.coef_

array([[  1.97923937e+03,   9.88644160e+03,  -4.66508774e+01,
          6.29951723e+03,   1.11960583e+04,   2.67470022e+01,
          9.65813588e+00,   4.93606902e+01,   1.21325250e+04,
          7.34815555e+03,   1.05453572e+01]])

In [17]:
ld.score(pf_cubic_train, y_train)
ld.score(pf_cubic_test, y_test)

0.75714582056838842

In [18]:
from sklearn.linear_model import Lasso
model_lasso = Lasso(alpha = 1000)
model_lasso.fit(pf_cubic_train, y_train)

Lasso(alpha=1000, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [19]:
model_lasso.intercept_
model_lasso.coef_

array([  2.16708977e+03,   1.01265081e+04,   3.16192094e+01,
         2.43055622e+03,   8.13149276e+03,   2.86923643e+01,
         8.53905149e+00,   5.10465465e+01,   1.02830458e+04,
         3.45804431e+03,   2.60946435e+01])

In [20]:
print('train: %.4f' % model_lasso.score(pf_cubic_train, y_train))
print('test : %.4f' % model_lasso.score(pf_cubic_test, y_test))

train: 0.8274
test : 0.7466


In [21]:
print('train: %.4f' % adjusted(model_lasso.score(pf_cubic_train, y_train), len(y_train), 11))
print('test : %.4f' % adjusted(model_lasso.score(pf_cubic_test, y_test), len(y_test), 11))

train: 0.8256
test : 0.7400
